### ISSUE TITLE
The Quake engine is probably incorrectly labeled as ID tech 1

### ISSUE THREAD

**Issue by Mogula99** [APHGames/slides#1]
According to all the sources I found, the Quake engine is labeled as ID tech 2.

The "mistake" is located [here](https://github.com/APHGames/slides/blob/main/slides/view/chapters/engines_history.pug).

Sources 
https://en.wikipedia.org/wiki/Id_Tech
https://www.ign.com/articles/2011/04/28/a-history-of-id-tech
https://www.youtube.com/watch?v=i86aGAvjtkA

**Comment by Mogula99** [comment]
The Doom engine is usually labeled as ID tech 1

**Comment by dodolab** [comment]
Thanks a lot! I had never noticed that Quake and Quake II were both made using the same IdTech2 engine but were distributed separately. Fixed.
