### ISSUE TITLE
Slides: The Czech version of engine scripting API is still in English

### ISSUE THREAD

**Issue by Mogula99** [APHGames/slides#2]
In the [last commit](https://github.com/APHGames/slides/commit/9e8a1ff16d5508dc336c8bcc70472a43aae40033#diff-5ba10e1cca3629ddf71267c88e43988224f98238d9b0ca69a9c0ad3b84cd8536) you've added the Czech version of the 2nd lecture. The slides about scripting API are still in English though. [This is the concerned file](https://github.com/APHGames/slides/blob/main/slides/view/chapters/engines_scripting_cs.pug).

**Comment by dodolab** [comment]
Thanks a lot for noticing. Fixed (and amended to the last commit 😄)
