### ISSUE TITLE
Lecture 6 - czech version - nitpicking

### ISSUE THREAD

**Issue by Mogula99** [APHGames/slides#5]
When referring to the Box-Muller algorithm (space_randomness_cs.pug - line 94), it would be great to have both initial letters capitalized (since those are the last names of the people who created the algorithm).

When describing how the cost function works in A* (space_navigation_cs.pug - line 147), it would be a tiny bit better to have a space between the word "Cost" and the first SVG file.

When mentioning categories of noise functions (space_procedural_cs.pug - line 125), it might make a little more sense to name the second category "Bodové" instead of "Bodový".

When you show the example of Perlin noise (space_procedural_cs.pug - line 132), you have the description "Perlinův **šun**" under the example.

**Comment by dodolab** [comment]
Thanks, will fix in 6.10.
