### ISSUE TITLE
Christmas time nitpicking

### ISSUE THREAD

**Issue by Mogula99** [APHGames/slides#6]
Lecture 7:
- physics_steering_cs.pug - line 12 - The guy who invented Steering behaviors was [Craig Reynolds](https://www.researchgate.net/publication/2495826_Steering_Behaviors_For_Autonomous_Characters), not Crag Reynolds.

Lecture 8:
- audio_music_cs.pug - line 77 - typo: sountrack -> soundtrack
                                   - line 81 - missing hyphen (-) between words "ostatní" and "např."
                                   - line 82 - missing space after hyphen (-)
                                   - line 163 - typo: úroveń -> úroveň

Lecture 10:
- gameai_introduction_cs.pug - line 110 - typo: akceptovatlené -> akceptovatelné

Lecture 11:
- multiplayer_transport_cs.pug - line 92 - typo: Každý jednotka -> každá jednotka
                                                 - line 155 - typo: mál obitů -> málo bitů

Thank you for the amazing course! Merry Christmas!

**Comment by dodolab** [comment]
Fixed 😆  thanks... will be deployed with the new APHWeb version in a few days
